version: '3.8'

services:
  # Backend API service
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./saves:/app/saves
      - ./.env:/app/.env
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    depends_on:
      - redis
    networks:
      - app-network

  # Redis for session storage and caching
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  # Nginx web server for frontend
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
